"""Refined constraints

Revision ID: 0cbc86275bf6
Revises: 3fc64185108d
Create Date: 2022-06-14 00:04:59.133969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '0cbc86275bf6'
down_revision = '3fc64185108d'
branch_labels = None
depends_on = None


def upgrade():
    filtertype_enum = postgresql.ENUM('Whitelist', 'Blacklist', name='filtertype', create_type=False)
    filtertype_enum.create(op.get_bind(), checkfirst=False)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spacetimelanguages',
    sa.Column('spacetimeconstraint_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['spacetimeconstraint_id'], ['spacetimeconstraint.id'], ),
    sa.PrimaryKeyConstraint('spacetimeconstraint_id', 'language_id')
    )
    op.add_column('constraintset', sa.Column('l_filter_type', sa.Enum('Whitelist', 'Blacklist', name='filtertype'), nullable=True))
    op.add_column('constraintset', sa.Column('u_filter_type', sa.Enum('Whitelist', 'Blacklist', name='filtertype'), nullable=True))
    op.drop_constraint('constraintset_spacetime_constraint_id_fkey', 'constraintset', type_='foreignkey')
    op.drop_column('constraintset', 'spacetime_constraint_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('constraintset', sa.Column('spacetime_constraint_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('constraintset_spacetime_constraint_id_fkey', 'constraintset', 'spacetimeconstraint', ['spacetime_constraint_id'], ['id'])
    op.drop_column('constraintset', 'u_filter_type')
    op.drop_column('constraintset', 'l_filter_type')
    op.drop_table('spacetimelanguages')
    # ### end Alembic commands ###
    postgresql.ENUM(name='filtertype').drop(op.get_bind(), checkfirst=False)