"""Added UserConstraintType

Revision ID: 0cc61735d4f7
Revises: baa258030e28
Create Date: 2022-06-11 22:27:21.477836

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '0cc61735d4f7'
down_revision = 'baa258030e28'
branch_labels = None
depends_on = None


def upgrade():
    userconstrainttype_enum = postgresql.ENUM('Whitelist', 'Blacklist', name='userconstrainttype', create_type=False)
    userconstrainttype_enum.create(op.get_bind(), checkfirst=False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('constraintset', sa.Column('user_constraint_type', sa.Enum('Whitelist', 'Blacklist', name='userconstrainttype'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('constraintset', 'user_constraint_type')
    # ### end Alembic commands ###
    postgresql.ENUM(name='userconstrainttype').drop(op.get_bind(), checkfirst=False)
