"""Added Problem, ProblemAttempt, Tag, etc.

Revision ID: 2156f137e421
Revises: d4867f3a4c0a
Create Date: 2022-05-25 12:26:25.299649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2156f137e421'
down_revision = 'd4867f3a4c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_id'), 'submission', ['id'], unique=False)
    op.create_table('problem',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('soft_linked', sa.Boolean(), nullable=True),
    sa.Column('head_commit', sa.String(length=40), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_head_commit'), 'problem', ['head_commit'], unique=False)
    op.create_index(op.f('ix_problem_id'), 'problem', ['id'], unique=False)
    op.create_index(op.f('ix_problem_slug'), 'problem', ['slug'], unique=True)
    op.create_index(op.f('ix_problem_title'), 'problem', ['title'], unique=False)
    op.create_table('tag',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_id'), 'tag', ['id'], unique=False)
    op.create_index(op.f('ix_tag_slug'), 'tag', ['slug'], unique=True)
    op.create_index(op.f('ix_tag_title'), 'tag', ['title'], unique=False)
    op.create_table('problemattempt',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('first_submission_id', sa.Integer(), nullable=True),
    sa.Column('effective_submission_id', sa.Integer(), nullable=True),
    sa.Column('active_submission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['active_submission_id'], ['submission.id'], ),
    sa.ForeignKeyConstraint(['effective_submission_id'], ['submission.id'], ),
    sa.ForeignKeyConstraint(['first_submission_id'], ['submission.id'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'problem_id'),
    sa.UniqueConstraint('problem_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('problemtags',
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('problem_id', 'tag_id'),
    sa.UniqueConstraint('problem_id'),
    sa.UniqueConstraint('tag_id')
    )
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_table('problemtags')
    op.drop_table('problemattempt')
    op.drop_index(op.f('ix_tag_title'), table_name='tag')
    op.drop_index(op.f('ix_tag_slug'), table_name='tag')
    op.drop_index(op.f('ix_tag_id'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_problem_title'), table_name='problem')
    op.drop_index(op.f('ix_problem_slug'), table_name='problem')
    op.drop_index(op.f('ix_problem_id'), table_name='problem')
    op.drop_index(op.f('ix_problem_head_commit'), table_name='problem')
    op.drop_table('problem')
    op.drop_index(op.f('ix_submission_id'), table_name='submission')
    op.drop_table('submission')
    # ### end Alembic commands ###
