"""Worked on constraints and contest models

Revision ID: 7cd22c4f3a4d
Revises: 88e2fa9ebf40
Create Date: 2022-06-10 22:32:16.947357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cd22c4f3a4d'
down_revision = '88e2fa9ebf40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constraintset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spacetime_constraint_id', sa.Integer(), nullable=True),
    sa.Column('timespan_constraint_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['spacetime_constraint_id'], ['spacetimeconstraint.id'], use_alter=True),
    sa.ForeignKeyConstraint(['timespan_constraint_id'], ['timespanconstraint.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spacetimeconstraint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cset_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('space', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cset_id'], ['constraintset.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timespanconstraint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cset_id', sa.Integer(), nullable=True),
    sa.Column('begin', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cset_id'], ['constraintset.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=True),
    sa.Column('title', sa.String(length=180), nullable=True),
    sa.Column('cset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cset_id'], ['constraintset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contest_id'), 'contest', ['id'], unique=False)
    op.create_index(op.f('ix_contest_slug'), 'contest', ['slug'], unique=True)
    op.create_table('userconstraint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cset_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cset_id'], ['constraintset.id'], use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('languageconstraint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cset_id', sa.Integer(), nullable=True),
    sa.Column('language_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cset_id'], ['constraintset.id'], use_alter=True),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('language', sa.Column('spacetime_constraint_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'language', 'spacetimeconstraint', ['spacetime_constraint_id'], ['id'])
    op.add_column('problem', sa.Column('is_forkable', sa.Boolean(), nullable=True))
    op.add_column('problem', sa.Column('difficulty', sa.Integer(), nullable=True))
    op.add_column('problem', sa.Column('constraintset_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'problem', 'constraintset', ['constraintset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'problem', type_='foreignkey')
    op.drop_column('problem', 'constraintset_id')
    op.drop_column('problem', 'difficulty')
    op.drop_column('problem', 'is_forkable')
    op.drop_constraint(None, 'language', type_='foreignkey')
    op.drop_column('language', 'spacetime_constraint_id')
    op.drop_table('languageconstraint')
    op.drop_table('userconstraint')
    op.drop_index(op.f('ix_contest_slug'), table_name='contest')
    op.drop_index(op.f('ix_contest_id'), table_name='contest')
    op.drop_table('contest')
    op.drop_table('timespanconstraint')
    op.drop_table('spacetimeconstraint')
    op.drop_table('constraintset')
    # ### end Alembic commands ###
