"""Added a test case count cold property to the problem model.

Revision ID: 88e2fa9ebf40
Revises: b3d67709238c
Create Date: 2022-06-10 09:32:48.236533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88e2fa9ebf40'
down_revision = 'b3d67709238c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('test_case_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem', 'test_case_count')
    # ### end Alembic commands ###
