"""User field

Revision ID: 94ddafbd3e88
Revises: c15bf6e7c5c4
Create Date: 2022-06-16 07:36:05.629703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ddafbd3e88'
down_revision = 'c15bf6e7c5c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('activated_once', sa.Boolean()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'activated_once')
    # ### end Alembic commands ###
