"""Creating foreign keys?

Revision ID: a31ce53e899c
Revises: 414e4e562aaf
Create Date: 2022-06-15 02:46:36.527279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a31ce53e899c'
down_revision = '414e4e562aaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    op.create_foreign_key(
        "fkey_submission_problemattempt",
        "submission", "problemattempt",
        ["user_id", "problem_id"],
        ["user_id", "problem_id"],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    op.drop_constraint("fkey_submission_problemattempt", "submission", type_="foreignkey")
