"""Added Judger, Language and Submission

Revision ID: ae9c73dcc768
Revises: 2156f137e421
Create Date: 2022-05-25 18:32:58.961558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae9c73dcc768'
down_revision = '2156f137e421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_language_id'), 'language', ['id'], unique=False)
    op.create_table('judger',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_judger_id'), 'judger', ['id'], unique=False)
    op.create_table('judgerlanguage',
    sa.Column('judger_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['judger_id'], ['judger.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.PrimaryKeyConstraint('judger_id', 'language_id')
    )
    op.add_column('problem', sa.Column('fork_of_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'problem', 'problem', ['fork_of_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'problem', type_='foreignkey')
    op.drop_column('problem', 'fork_of_id')
    op.drop_table('judgerlanguage')
    op.drop_index(op.f('ix_judger_id'), table_name='judger')
    op.drop_table('judger')
    op.drop_index(op.f('ix_language_id'), table_name='language')
    op.drop_table('language')
    # ### end Alembic commands ###
