"""Changed linking entities and added user intersts.

Revision ID: b3d67709238c
Revises: cc4b9b53bc09
Create Date: 2022-06-09 08:40:29.954738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d67709238c'
down_revision = 'cc4b9b53bc09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userinterests',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'tag_id')
    )
    op.drop_constraint('problemtags_problem_id_key', 'problemtags', type_='unique')
    op.drop_constraint('problemtags_tag_id_key', 'problemtags', type_='unique')
    op.drop_constraint('userroles_role_id_key', 'userroles', type_='unique')
    op.drop_constraint('userroles_user_id_key', 'userroles', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('userroles_user_id_key', 'userroles', ['user_id'])
    op.create_unique_constraint('userroles_role_id_key', 'userroles', ['role_id'])
    op.create_unique_constraint('problemtags_tag_id_key', 'problemtags', ['tag_id'])
    op.create_unique_constraint('problemtags_problem_id_key', 'problemtags', ['problem_id'])
    op.drop_table('userinterests')
    # ### end Alembic commands ###
