"""Added contest field to problem.

Revision ID: baa258030e28
Revises: 7cd22c4f3a4d
Create Date: 2022-06-11 02:07:40.642794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baa258030e28'
down_revision = '7cd22c4f3a4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'constraintset', 'spacetimeconstraint', ['spacetime_constraint_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'constraintset', 'timespanconstraint', ['timespan_constraint_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'languageconstraint', 'constraintset', ['cset_id'], ['id'], use_alter=True)
    op.add_column('problem', sa.Column('contest_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'problem', 'contest', ['contest_id'], ['id'])
    op.create_foreign_key(None, 'spacetimeconstraint', 'constraintset', ['cset_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'timespanconstraint', 'constraintset', ['cset_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'userconstraint', 'constraintset', ['cset_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userconstraint', type_='foreignkey')
    op.drop_constraint(None, 'timespanconstraint', type_='foreignkey')
    op.drop_constraint(None, 'spacetimeconstraint', type_='foreignkey')
    op.drop_constraint(None, 'problem', type_='foreignkey')
    op.drop_column('problem', 'contest_id')
    op.drop_constraint(None, 'languageconstraint', type_='foreignkey')
    op.drop_constraint(None, 'constraintset', type_='foreignkey')
    op.drop_constraint(None, 'constraintset', type_='foreignkey')
    # ### end Alembic commands ###
