"""Additional user fields

Revision ID: c15bf6e7c5c4
Revises: a31ce53e899c
Create Date: 2022-06-15 09:48:00.230140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'c15bf6e7c5c4'
down_revision = 'a31ce53e899c'
branch_labels = None
depends_on = None


def upgrade():
    gender_enum = postgresql.ENUM('Male', 'Female', "Other", "NotSpecified", name='gender', create_type=False)
    gender_enum.create(op.get_bind(), checkfirst=False)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('gender', sa.Enum('Male', 'Female', 'Other', 'NotSpecified', name='gender'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gender')
    op.drop_column('user', 'bio')
    # ### end Alembic commands ###
    postgresql.ENUM(name='gender').drop(op.get_bind(), checkfirst=False)
