"""Added language placeholder

Revision ID: cc4b9b53bc09
Revises: 6a87dbd51b3a
Create Date: 2022-06-08 22:09:58.238567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc4b9b53bc09'
down_revision = '6a87dbd51b3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language', sa.Column('placeholder', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('language', 'placeholder')
    # ### end Alembic commands ###
