
version: "3.3"
services:
  frontend:
    volumes:
      - ./scripts/dev/nginx.dev.conf:/etc/nginx/conf.d/default.conf 
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - traefik.enable=true
      - traefik.constraint-label-stack=${TRAEFIK_TAG?Variable not set}
      - traefik.http.routers.${STACK_NAME?Variable not set}-frontend-http.rule=PathPrefix(`/`)
      - traefik.http.services.${STACK_NAME?Variable not set}-frontend.loadbalancer.server.port=80

  backend: 
    ports:
      - "5678:5678"
    volumes:
      - ./backend/app:/app